-- ============================================================================
-- ⚠️ OBSOLETO — NÃO RODAR ESTE ARQUIVO.
--
-- Este arquivo criava uma empresa "vazia" automaticamente a cada signup, o
-- que exigia relaxar as validações de CNPJ/IBGE no banco.
--
-- Foi substituído pela abordagem melhor em `supabase_onboarding.sql`:
-- o usuário preenche os dados reais na tela /onboarding no primeiro login,
-- e a função `criar_minha_empresa()` cria tudo de uma vez, com validação.
--
-- Pode apagar este arquivo.
-- ============================================================================
